/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package telaprincipal;

import java.awt.GraphicsEnvironment;

/**
 *
 * @author Robson Cavalcante
 */
public class TelaPrincipal1 extends javax.swing.JFrame {

    /**
     * Creates new form TelaPrincipal1
     */
    public TelaPrincipal1() {
        initComponents();
        setLocationRelativeTo(null);
         //funcao responsavel por redimensionar a tela de acordo com a resoloucao.
        //GraphicsEnvironment.getLocalGraphicsEnvironment().getDefaultScreenDevice().getDisplayMode() ;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTesteGif1 = new javax.swing.JLabel();
        jTesteGif = new javax.swing.JLabel();
        jLCorrecaoGif = new javax.swing.JLabel();
        jLNomeDoJagador2 = new javax.swing.JLabel();
        jLNomeDoJagador1 = new javax.swing.JLabel();
        jSPossesjogador1 = new javax.swing.JScrollPane();
        jSPossesjogador2 = new javax.swing.JScrollPane();
        jLLogradouro11 = new javax.swing.JLabel();
        jLLogradouro12 = new javax.swing.JLabel();
        jLLogradouro13 = new javax.swing.JLabel();
        jLLogradouro14 = new javax.swing.JLabel();
        jLLogradouro15 = new javax.swing.JLabel();
        jLLogradouro16 = new javax.swing.JLabel();
        jLLogradouro17 = new javax.swing.JLabel();
        jLLogradouro18 = new javax.swing.JLabel();
        jLLogradouro19 = new javax.swing.JLabel();
        jLLogradouro0 = new javax.swing.JLabel();
        jLLogradouro1 = new javax.swing.JLabel();
        jLLogradouro2 = new javax.swing.JLabel();
        jLLogradouro3 = new javax.swing.JLabel();
        jLLogradouro6 = new javax.swing.JLabel();
        jLLogradouro7 = new javax.swing.JLabel();
        jLLogradouro8 = new javax.swing.JLabel();
        jLLogradouro9 = new javax.swing.JLabel();
        jLLogradouro10 = new javax.swing.JLabel();
        jLLogradouro4 = new javax.swing.JLabel();
        jLLogradouro5 = new javax.swing.JLabel();
        jLCartasJogador1 = new javax.swing.JLabel();
        jLCartasJogador2 = new javax.swing.JLabel();
        jLImagemCentral = new javax.swing.JLabel();
        jLPersonagem2 = new javax.swing.JLabel();
        jLPersonagem1 = new javax.swing.JLabel();
        jBFinalizarJogada1 = new javax.swing.JButton();
        jBFinalizarJogada2 = new javax.swing.JButton();
        jCDado1Jogador2 = new javax.swing.JComboBox();
        jCDado2Jogador2 = new javax.swing.JComboBox();
        jCDado1Jogador1 = new javax.swing.JComboBox();
        jCDado2Jogador1 = new javax.swing.JComboBox();
        jLTabuleiro = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        setMaximumSize(new java.awt.Dimension(1376, 728));
        setMinimumSize(new java.awt.Dimension(1376, 728));
        setUndecorated(true);
        addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                formKeyTyped(evt);
            }
        });
        getContentPane().setLayout(null);

        jTesteGif1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/Costas.gif"))); // NOI18N
        getContentPane().add(jTesteGif1);
        jTesteGif1.setBounds(340, 630, 50, 49);

        jTesteGif.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/Conversa.gif"))); // NOI18N
        getContentPane().add(jTesteGif);
        jTesteGif.setBounds(390, 630, 50, 50);

        jLCorrecaoGif.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/CorreçãoDoGif.gif"))); // NOI18N
        getContentPane().add(jLCorrecaoGif);
        jLCorrecaoGif.setBounds(490, 360, 400, 155);

        jLNomeDoJagador2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/ArwenOuro.png"))); // NOI18N
        getContentPane().add(jLNomeDoJagador2);
        jLNomeDoJagador2.setBounds(1270, 160, 90, 20);

        jLNomeDoJagador1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/FrodoOuro.png"))); // NOI18N
        getContentPane().add(jLNomeDoJagador1);
        jLNomeDoJagador1.setBounds(120, 160, 96, 20);
        getContentPane().add(jSPossesjogador1);
        jSPossesjogador1.setBounds(40, 513, 160, 190);
        getContentPane().add(jSPossesjogador2);
        jSPossesjogador2.setBounds(1173, 513, 160, 190);

        jLLogradouro11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/olho-de-sauron.jpg"))); // NOI18N
        getContentPane().add(jLLogradouro11);
        jLLogradouro11.setBounds(930, 120, 120, 120);

        jLLogradouro12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/olho-de-sauron.jpg"))); // NOI18N
        getContentPane().add(jLLogradouro12);
        jLLogradouro12.setBounds(930, 240, 120, 120);

        jLLogradouro13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/olho-de-sauron.jpg"))); // NOI18N
        getContentPane().add(jLLogradouro13);
        jLLogradouro13.setBounds(930, 360, 120, 120);

        jLLogradouro14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/olho-de-sauron.jpg"))); // NOI18N
        getContentPane().add(jLLogradouro14);
        jLLogradouro14.setBounds(930, 480, 120, 120);

        jLLogradouro15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/olho-de-sauron.jpg"))); // NOI18N
        getContentPane().add(jLLogradouro15);
        jLLogradouro15.setBounds(930, 600, 120, 120);

        jLLogradouro16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/olho-de-sauron.jpg"))); // NOI18N
        getContentPane().add(jLLogradouro16);
        jLLogradouro16.setBounds(810, 600, 120, 120);

        jLLogradouro17.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/olho-de-sauron.jpg"))); // NOI18N
        getContentPane().add(jLLogradouro17);
        jLLogradouro17.setBounds(690, 600, 120, 120);

        jLLogradouro18.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/olho-de-sauron.jpg"))); // NOI18N
        getContentPane().add(jLLogradouro18);
        jLLogradouro18.setBounds(570, 600, 120, 120);

        jLLogradouro19.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/olho-de-sauron.jpg"))); // NOI18N
        getContentPane().add(jLLogradouro19);
        jLLogradouro19.setBounds(450, 600, 120, 120);

        jLLogradouro0.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/olho-de-sauron.jpg"))); // NOI18N
        getContentPane().add(jLLogradouro0);
        jLLogradouro0.setBounds(330, 600, 120, 120);

        jLLogradouro1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/olho-de-sauron.jpg"))); // NOI18N
        getContentPane().add(jLLogradouro1);
        jLLogradouro1.setBounds(330, 480, 120, 120);

        jLLogradouro2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/olho-de-sauron.jpg"))); // NOI18N
        getContentPane().add(jLLogradouro2);
        jLLogradouro2.setBounds(330, 360, 120, 120);

        jLLogradouro3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/olho-de-sauron.jpg"))); // NOI18N
        getContentPane().add(jLLogradouro3);
        jLLogradouro3.setBounds(330, 240, 120, 120);

        jLLogradouro6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/olho-de-sauron.jpg"))); // NOI18N
        getContentPane().add(jLLogradouro6);
        jLLogradouro6.setBounds(450, 0, 120, 120);

        jLLogradouro7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/olho-de-sauron.jpg"))); // NOI18N
        getContentPane().add(jLLogradouro7);
        jLLogradouro7.setBounds(570, 0, 120, 120);

        jLLogradouro8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/olho-de-sauron.jpg"))); // NOI18N
        getContentPane().add(jLLogradouro8);
        jLLogradouro8.setBounds(690, 0, 120, 120);

        jLLogradouro9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/olho-de-sauron.jpg"))); // NOI18N
        getContentPane().add(jLLogradouro9);
        jLLogradouro9.setBounds(810, 0, 120, 120);

        jLLogradouro10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/olho-de-sauron.jpg"))); // NOI18N
        getContentPane().add(jLLogradouro10);
        jLLogradouro10.setBounds(930, 0, 120, 120);

        jLLogradouro4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/olho-de-sauron.jpg"))); // NOI18N
        getContentPane().add(jLLogradouro4);
        jLLogradouro4.setBounds(330, 120, 120, 120);

        jLLogradouro5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/olho-de-sauron.jpg"))); // NOI18N
        getContentPane().add(jLLogradouro5);
        jLLogradouro5.setBounds(330, 0, 120, 120);

        jLCartasJogador1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/olho-de-sauron.jpg"))); // NOI18N
        getContentPane().add(jLCartasJogador1);
        jLCartasJogador1.setBounds(20, 295, 190, 190);

        jLCartasJogador2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/olho-de-sauron.jpg"))); // NOI18N
        getContentPane().add(jLCartasJogador2);
        jLCartasJogador2.setBounds(1170, 300, 190, 190);

        jLImagemCentral.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/Olho.gif"))); // NOI18N
        getContentPane().add(jLImagemCentral);
        jLImagemCentral.setBounds(490, 120, 410, 480);

        jLPersonagem2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/Arwen.png"))); // NOI18N
        getContentPane().add(jLPersonagem2);
        jLPersonagem2.setBounds(1130, 60, 160, 120);

        jLPersonagem1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/Frodo.png"))); // NOI18N
        getContentPane().add(jLPersonagem1);
        jLPersonagem1.setBounds(-20, 60, 160, 120);

        jBFinalizarJogada1.setBackground(new java.awt.Color(51, 51, 0));
        jBFinalizarJogada1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/botãonormal.png"))); // NOI18N
        getContentPane().add(jBFinalizarJogada1);
        jBFinalizarJogada1.setBounds(30, 190, 170, 40);

        jBFinalizarJogada2.setBackground(new java.awt.Color(51, 51, 0));
        jBFinalizarJogada2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/botãonormal.png"))); // NOI18N
        getContentPane().add(jBFinalizarJogada2);
        jBFinalizarJogada2.setBounds(1170, 190, 170, 40);

        jCDado1Jogador2.setBackground(new java.awt.Color(102, 102, 102));
        jCDado1Jogador2.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "1", "2", "3", "4", "5", "6" }));
        jCDado1Jogador2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCDado1Jogador2ActionPerformed(evt);
            }
        });
        getContentPane().add(jCDado1Jogador2);
        jCDado1Jogador2.setBounds(1260, 30, 40, 20);

        jCDado2Jogador2.setBackground(new java.awt.Color(102, 102, 102));
        jCDado2Jogador2.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "1", "2", "3", "4", "5", "6" }));
        getContentPane().add(jCDado2Jogador2);
        jCDado2Jogador2.setBounds(1310, 30, 40, 20);

        jCDado1Jogador1.setBackground(new java.awt.Color(102, 102, 102));
        jCDado1Jogador1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "1", "2", "3", "4", "5", "6" }));
        getContentPane().add(jCDado1Jogador1);
        jCDado1Jogador1.setBounds(170, 30, 40, 20);

        jCDado2Jogador1.setBackground(new java.awt.Color(102, 102, 102));
        jCDado2Jogador1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "1", "2", "3", "4", "5", "6" }));
        jCDado2Jogador1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCDado2Jogador1ActionPerformed(evt);
            }
        });
        getContentPane().add(jCDado2Jogador1);
        jCDado2Jogador1.setBounds(120, 30, 40, 20);

        jLTabuleiro.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/Tabuleiro1jL.png"))); // NOI18N
        jLTabuleiro.setMaximumSize(new java.awt.Dimension(1376, 728));
        jLTabuleiro.setMinimumSize(new java.awt.Dimension(1376, 728));
        jLTabuleiro.setPreferredSize(new java.awt.Dimension(1376, 728));
        getContentPane().add(jLTabuleiro);
        jLTabuleiro.setBounds(0, 0, 1376, 728);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jCDado2Jogador1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCDado2Jogador1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCDado2Jogador1ActionPerformed

    private void jCDado1Jogador2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCDado1Jogador2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCDado1Jogador2ActionPerformed

    private void formKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_formKeyTyped
        System.out.println(evt.getKeyCode());
    }//GEN-LAST:event_formKeyTyped

    private void movimentar(int posicoes){
        
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaPrincipal1().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBFinalizarJogada1;
    private javax.swing.JButton jBFinalizarJogada2;
    private javax.swing.JComboBox jCDado1Jogador1;
    private javax.swing.JComboBox jCDado1Jogador2;
    private javax.swing.JComboBox jCDado2Jogador1;
    private javax.swing.JComboBox jCDado2Jogador2;
    private javax.swing.JLabel jLCartasJogador1;
    private javax.swing.JLabel jLCartasJogador2;
    private javax.swing.JLabel jLCorrecaoGif;
    private javax.swing.JLabel jLImagemCentral;
    private javax.swing.JLabel jLLogradouro0;
    private javax.swing.JLabel jLLogradouro1;
    private javax.swing.JLabel jLLogradouro10;
    private javax.swing.JLabel jLLogradouro11;
    private javax.swing.JLabel jLLogradouro12;
    private javax.swing.JLabel jLLogradouro13;
    private javax.swing.JLabel jLLogradouro14;
    private javax.swing.JLabel jLLogradouro15;
    private javax.swing.JLabel jLLogradouro16;
    private javax.swing.JLabel jLLogradouro17;
    private javax.swing.JLabel jLLogradouro18;
    private javax.swing.JLabel jLLogradouro19;
    private javax.swing.JLabel jLLogradouro2;
    private javax.swing.JLabel jLLogradouro3;
    private javax.swing.JLabel jLLogradouro4;
    private javax.swing.JLabel jLLogradouro5;
    private javax.swing.JLabel jLLogradouro6;
    private javax.swing.JLabel jLLogradouro7;
    private javax.swing.JLabel jLLogradouro8;
    private javax.swing.JLabel jLLogradouro9;
    private javax.swing.JLabel jLNomeDoJagador1;
    private javax.swing.JLabel jLNomeDoJagador2;
    private javax.swing.JLabel jLPersonagem1;
    private javax.swing.JLabel jLPersonagem2;
    private javax.swing.JLabel jLTabuleiro;
    private javax.swing.JScrollPane jSPossesjogador1;
    private javax.swing.JScrollPane jSPossesjogador2;
    private javax.swing.JLabel jTesteGif;
    private javax.swing.JLabel jTesteGif1;
    // End of variables declaration//GEN-END:variables
}
