/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package ufc.projeto.visao;

import ufc.projeto.visao.criacao.ImpleMapaPosicoesTabuleiroGui;
import java.awt.GraphicsEnvironment;
import java.awt.Point;
import java.net.URL;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.Iterator;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import ufc.projeto.modelo.AcoesDoJogo;
import ufc.projeto.modelo.BancoImobiliario;
import ufc.projeto.modelo.ImpleBancoImobiliario;
import ufc.projeto.modelo.ImpleJogador;
import ufc.projeto.modelo.ImpleTabuleiro;
import ufc.projeto.modelo.Jogador;
import ufc.projeto.modelo.Logradouro;
import ufc.projeto.modelo.LogradouroAdquirivel;
import ufc.projeto.modelo.Tabuleiro;
import ufc.projeto.modelo.excecoes.JogadorSemSaldoException;
import ufc.projeto.modelo.excecoes.LogradouroNaoPodeSerAdquiridoException;
import ufc.projeto.modelo.excecoes.LogradouroSemPrecoException;
import ufc.projeto.modelo.excecoes.PosicaoIvalidaParaLogradouroException;
import ufc.projeto.modelo.excecoes.PropriedadeJaAdquiridaException;
import ufc.projeto.visao.controladores.midia.ControladorDeAudio;
import ufc.projeto.visao.dialogos.DialogoLogradouro;
import ufc.projeto.visao.dialogos.criacao.CriadorDialogo;
import ufc.projeto.visao.enumeracoes.Jogadores;
import ufc.projeto.visao.enumeracoes.Midia;
import ufc.projeto.visao.enumeracoes.MovimentacaoPersonagemGui;
import ufc.projeto.modelo.Perfil;
import ufc.projeto.visao.dialogos.DialogoMostrarLogradouro;


/**
 *
 * @author Robson Cavalcante
 */
public class BancoImobiliarioGui extends javax.swing.JFrame implements AcoesDoJogo{

    /**
     * Creates new form TelaPrincipal1
     */
    
    private final HashMap<Point, Integer> pontosLogradourosGui;
    private final BancoImobiliario mBancoImobiliario;
    private final List<Jogador> listaJogadores;
    
    
    public BancoImobiliarioGui(List<Perfil> perfil){
        initComponents();
        setLocationRelativeTo(null);
         //funcao responsavel por redimensionar a tela de acordo com a resoloucao.
        GraphicsEnvironment.getLocalGraphicsEnvironment().getDefaultScreenDevice().getDisplayMode() ;
        
        pontosLogradourosGui = new ImpleMapaPosicoesTabuleiroGui().obterPosicoes();
        listaJogadores = new ArrayList<>();
        Tabuleiro tabuleiro = new ImpleTabuleiro();
        
        listaJogadores.add(new ImpleJogador(perfil.get(Jogadores.JOGADOR_1.obterValor()), tabuleiro));
        listaJogadores.add(new ImpleJogador(perfil.get(Jogadores.JOGADOR_2.obterValor()), tabuleiro));
        
        mBancoImobiliario = new ImpleBancoImobiliario(listaJogadores,tabuleiro,this);
        preenchendoPerfil(perfil);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLPersonagemJogador1 = new javax.swing.JLabel();
        jLCorrecaoGif = new javax.swing.JLabel();
        jLPersonagemJogador2 = new javax.swing.JLabel();
        jLNomeDoJagador2 = new javax.swing.JLabel();
        jLNomeDoJagador1 = new javax.swing.JLabel();
        jSPossesjogador1 = new javax.swing.JScrollPane();
        PTPossesJogador1 = new javax.swing.JTextPane();
        jSPossesjogador2 = new javax.swing.JScrollPane();
        PTPossesJogador2 = new javax.swing.JTextPane();
        jLLogradouro11 = new javax.swing.JLabel();
        jLLogradouro12 = new javax.swing.JLabel();
        jLLogradouro13 = new javax.swing.JLabel();
        jLLogradouro14 = new javax.swing.JLabel();
        jLLogradouro15 = new javax.swing.JLabel();
        jLLogradouro16 = new javax.swing.JLabel();
        jLLogradouro17 = new javax.swing.JLabel();
        jLLogradouro18 = new javax.swing.JLabel();
        jLLogradouro19 = new javax.swing.JLabel();
        jLLogradouro0 = new javax.swing.JLabel();
        jLLogradouro1 = new javax.swing.JLabel();
        jLLogradouro2 = new javax.swing.JLabel();
        jLLogradouro3 = new javax.swing.JLabel();
        jLLogradouro6 = new javax.swing.JLabel();
        jLLogradouro7 = new javax.swing.JLabel();
        jLLogradouro8 = new javax.swing.JLabel();
        jLLogradouro9 = new javax.swing.JLabel();
        jLLogradouro10 = new javax.swing.JLabel();
        jLLogradouro4 = new javax.swing.JLabel();
        jLLogradouro5 = new javax.swing.JLabel();
        jLCartasJogador1 = new javax.swing.JLabel();
        jLCartasJogador2 = new javax.swing.JLabel();
        jLImagemCentral = new javax.swing.JLabel();
        jLPersonagem2 = new javax.swing.JLabel();
        jLPersonagem1 = new javax.swing.JLabel();
        jBFinalizarJogada1 = new javax.swing.JButton();
        jBFinalizarJogada2 = new javax.swing.JButton();
        jCDado1Jogador2 = new javax.swing.JComboBox();
        jCDado2Jogador2 = new javax.swing.JComboBox();
        jCDado2Jogador1 = new javax.swing.JComboBox();
        jCDado1Jogador1 = new javax.swing.JComboBox();
        jLSaldoJogador1 = new javax.swing.JLabel();
        jLSaldoJogador2 = new javax.swing.JLabel();
        jLposicaoDialogoComprar = new javax.swing.JLabel();
        jLTabuleiro = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        setMinimumSize(new java.awt.Dimension(1376, 728));
        setUndecorated(true);
        addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                formKeyTyped(evt);
            }
        });
        getContentPane().setLayout(null);

        jLPersonagemJogador1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ufc/projeto/imagens/personagens/Costas.gif"))); // NOI18N
        getContentPane().add(jLPersonagemJogador1);
        jLPersonagemJogador1.setBounds(340, 630, 50, 85);

        jLCorrecaoGif.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ufc/projeto/imagens/background/CorreçãoDoGif.gif"))); // NOI18N
        getContentPane().add(jLCorrecaoGif);
        jLCorrecaoGif.setBounds(490, 360, 400, 155);

        jLPersonagemJogador2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ufc/projeto/imagens/personagens/Conversa.gif"))); // NOI18N
        getContentPane().add(jLPersonagemJogador2);
        jLPersonagemJogador2.setBounds(390, 630, 50, 85);

        jLNomeDoJagador2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ufc/projeto/imagens/background/LegolasNome.png"))); // NOI18N
        getContentPane().add(jLNomeDoJagador2);
        jLNomeDoJagador2.setBounds(1270, 160, 90, 20);

        jLNomeDoJagador1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ufc/projeto/imagens/background/GandalfNome.png"))); // NOI18N
        getContentPane().add(jLNomeDoJagador1);
        jLNomeDoJagador1.setBounds(118, 160, 96, 20);

        PTPossesJogador1.setEditable(false);
        jSPossesjogador1.setViewportView(PTPossesJogador1);

        getContentPane().add(jSPossesjogador1);
        jSPossesjogador1.setBounds(29, 510, 175, 190);

        PTPossesJogador2.setEditable(false);
        jSPossesjogador2.setViewportView(PTPossesJogador2);

        getContentPane().add(jSPossesjogador2);
        jSPossesjogador2.setBounds(1173, 510, 175, 190);

        jLLogradouro11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ufc/projeto/imagens/background/olho-de-sauron.jpg"))); // NOI18N
        jLLogradouro11.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLLogradouro11MouseClicked(evt);
            }
        });
        getContentPane().add(jLLogradouro11);
        jLLogradouro11.setBounds(930, 124, 120, 120);

        jLLogradouro12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ufc/projeto/imagens/background/olho-de-sauron.jpg"))); // NOI18N
        jLLogradouro12.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLLogradouro12MouseClicked(evt);
            }
        });
        getContentPane().add(jLLogradouro12);
        jLLogradouro12.setBounds(930, 244, 120, 120);

        jLLogradouro13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ufc/projeto/imagens/background/olho-de-sauron.jpg"))); // NOI18N
        jLLogradouro13.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLLogradouro13MouseClicked(evt);
            }
        });
        getContentPane().add(jLLogradouro13);
        jLLogradouro13.setBounds(930, 364, 120, 120);

        jLLogradouro14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ufc/projeto/imagens/background/olho-de-sauron.jpg"))); // NOI18N
        jLLogradouro14.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLLogradouro14MouseClicked(evt);
            }
        });
        getContentPane().add(jLLogradouro14);
        jLLogradouro14.setBounds(930, 484, 120, 120);

        jLLogradouro15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ufc/projeto/imagens/background/olho-de-sauron.jpg"))); // NOI18N
        jLLogradouro15.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLLogradouro15MouseClicked(evt);
            }
        });
        getContentPane().add(jLLogradouro15);
        jLLogradouro15.setBounds(930, 604, 120, 120);

        jLLogradouro16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ufc/projeto/imagens/background/olho-de-sauron.jpg"))); // NOI18N
        jLLogradouro16.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLLogradouro16MouseClicked(evt);
            }
        });
        jLLogradouro16.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jLLogradouro16KeyPressed(evt);
            }
        });
        getContentPane().add(jLLogradouro16);
        jLLogradouro16.setBounds(810, 604, 120, 120);

        jLLogradouro17.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ufc/projeto/imagens/background/olho-de-sauron.jpg"))); // NOI18N
        jLLogradouro17.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLLogradouro17MouseClicked(evt);
            }
        });
        getContentPane().add(jLLogradouro17);
        jLLogradouro17.setBounds(690, 604, 120, 120);

        jLLogradouro18.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ufc/projeto/imagens/background/olho-de-sauron.jpg"))); // NOI18N
        jLLogradouro18.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLLogradouro18MouseClicked(evt);
            }
        });
        getContentPane().add(jLLogradouro18);
        jLLogradouro18.setBounds(570, 604, 120, 120);

        jLLogradouro19.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ufc/projeto/imagens/background/olho-de-sauron.jpg"))); // NOI18N
        jLLogradouro19.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLLogradouro19MouseClicked(evt);
            }
        });
        getContentPane().add(jLLogradouro19);
        jLLogradouro19.setBounds(450, 604, 120, 120);

        jLLogradouro0.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ufc/projeto/imagens/background/olho-de-sauron.jpg"))); // NOI18N
        jLLogradouro0.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLLogradouro0MouseClicked(evt);
            }
        });
        getContentPane().add(jLLogradouro0);
        jLLogradouro0.setBounds(330, 604, 120, 120);

        jLLogradouro1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ufc/projeto/imagens/background/olho-de-sauron.jpg"))); // NOI18N
        jLLogradouro1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLLogradouro1MouseClicked(evt);
            }
        });
        getContentPane().add(jLLogradouro1);
        jLLogradouro1.setBounds(330, 484, 120, 120);

        jLLogradouro2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ufc/projeto/imagens/background/olho-de-sauron.jpg"))); // NOI18N
        jLLogradouro2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLLogradouro2MouseClicked(evt);
            }
        });
        getContentPane().add(jLLogradouro2);
        jLLogradouro2.setBounds(330, 364, 120, 120);

        jLLogradouro3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ufc/projeto/imagens/background/olho-de-sauron.jpg"))); // NOI18N
        jLLogradouro3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLLogradouro3MouseClicked(evt);
            }
        });
        getContentPane().add(jLLogradouro3);
        jLLogradouro3.setBounds(330, 244, 120, 120);

        jLLogradouro6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ufc/projeto/imagens/background/olho-de-sauron.jpg"))); // NOI18N
        jLLogradouro6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLLogradouro6MouseClicked(evt);
            }
        });
        getContentPane().add(jLLogradouro6);
        jLLogradouro6.setBounds(450, 4, 120, 120);

        jLLogradouro7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ufc/projeto/imagens/background/olho-de-sauron.jpg"))); // NOI18N
        jLLogradouro7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLLogradouro7MouseClicked(evt);
            }
        });
        getContentPane().add(jLLogradouro7);
        jLLogradouro7.setBounds(570, 4, 120, 120);

        jLLogradouro8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ufc/projeto/imagens/background/olho-de-sauron.jpg"))); // NOI18N
        jLLogradouro8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLLogradouro8MouseClicked(evt);
            }
        });
        getContentPane().add(jLLogradouro8);
        jLLogradouro8.setBounds(690, 4, 120, 120);

        jLLogradouro9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ufc/projeto/imagens/background/olho-de-sauron.jpg"))); // NOI18N
        jLLogradouro9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLLogradouro9MouseClicked(evt);
            }
        });
        getContentPane().add(jLLogradouro9);
        jLLogradouro9.setBounds(810, 4, 120, 120);

        jLLogradouro10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ufc/projeto/imagens/background/olho-de-sauron.jpg"))); // NOI18N
        jLLogradouro10.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLLogradouro10MouseClicked(evt);
            }
        });
        getContentPane().add(jLLogradouro10);
        jLLogradouro10.setBounds(930, 4, 120, 120);

        jLLogradouro4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ufc/projeto/imagens/background/olho-de-sauron.jpg"))); // NOI18N
        jLLogradouro4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLLogradouro4MouseClicked(evt);
            }
        });
        getContentPane().add(jLLogradouro4);
        jLLogradouro4.setBounds(330, 124, 120, 120);

        jLLogradouro5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ufc/projeto/imagens/background/olho-de-sauron.jpg"))); // NOI18N
        jLLogradouro5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLLogradouro5MouseClicked(evt);
            }
        });
        getContentPane().add(jLLogradouro5);
        jLLogradouro5.setBounds(330, 4, 120, 120);

        jLCartasJogador1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ufc/projeto/imagens/background/olho-de-sauron.jpg"))); // NOI18N
        getContentPane().add(jLCartasJogador1);
        jLCartasJogador1.setBounds(30, 290, 170, 180);

        jLCartasJogador2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ufc/projeto/imagens/background/olho-de-sauron.jpg"))); // NOI18N
        getContentPane().add(jLCartasJogador2);
        jLCartasJogador2.setBounds(1175, 290, 170, 180);

        jLImagemCentral.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ufc/projeto/imagens/background/Olho.gif"))); // NOI18N
        getContentPane().add(jLImagemCentral);
        jLImagemCentral.setBounds(490, 120, 410, 480);

        jLPersonagem2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ufc/projeto/imagens/personagens/Legolas.png"))); // NOI18N
        getContentPane().add(jLPersonagem2);
        jLPersonagem2.setBounds(1130, 60, 160, 120);

        jLPersonagem1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ufc/projeto/imagens/personagens/Gandalf.png"))); // NOI18N
        getContentPane().add(jLPersonagem1);
        jLPersonagem1.setBounds(-22, 60, 160, 120);

        jBFinalizarJogada1.setBackground(new java.awt.Color(51, 51, 0));
        jBFinalizarJogada1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ufc/projeto/imagens/botoes/JogarRodadaNormal.png"))); // NOI18N
        jBFinalizarJogada1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jBFinalizarJogada1MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jBFinalizarJogada1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jBFinalizarJogada1MouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jBFinalizarJogada1MousePressed(evt);
            }
        });
        jBFinalizarJogada1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBFinalizarJogada1ActionPerformed(evt);
            }
        });
        getContentPane().add(jBFinalizarJogada1);
        jBFinalizarJogada1.setBounds(30, 190, 170, 40);

        jBFinalizarJogada2.setBackground(new java.awt.Color(51, 51, 0));
        jBFinalizarJogada2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ufc/projeto/imagens/botoes/JogarRodadaNormal.png"))); // NOI18N
        jBFinalizarJogada2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jBFinalizarJogada2MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jBFinalizarJogada2MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jBFinalizarJogada2MouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jBFinalizarJogada2MousePressed(evt);
            }
        });
        jBFinalizarJogada2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBFinalizarJogada2ActionPerformed(evt);
            }
        });
        getContentPane().add(jBFinalizarJogada2);
        jBFinalizarJogada2.setBounds(1175, 189, 170, 40);

        jCDado1Jogador2.setBackground(new java.awt.Color(102, 102, 102));
        jCDado1Jogador2.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "1", "2", "3" }));
        jCDado1Jogador2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCDado1Jogador2ActionPerformed(evt);
            }
        });
        getContentPane().add(jCDado1Jogador2);
        jCDado1Jogador2.setBounds(1260, 30, 40, 20);

        jCDado2Jogador2.setBackground(new java.awt.Color(102, 102, 102));
        jCDado2Jogador2.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "1", "2", "3" }));
        getContentPane().add(jCDado2Jogador2);
        jCDado2Jogador2.setBounds(1310, 30, 40, 20);

        jCDado2Jogador1.setBackground(new java.awt.Color(102, 102, 102));
        jCDado2Jogador1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "1", "2", "3", "4", "5", "6" }));
        getContentPane().add(jCDado2Jogador1);
        jCDado2Jogador1.setBounds(170, 30, 40, 20);

        jCDado1Jogador1.setBackground(new java.awt.Color(102, 102, 102));
        jCDado1Jogador1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "1", "2", "3", "4", "5", "6" }));
        jCDado1Jogador1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCDado1Jogador1ActionPerformed(evt);
            }
        });
        getContentPane().add(jCDado1Jogador1);
        jCDado1Jogador1.setBounds(120, 30, 40, 20);

        jLSaldoJogador1.setFont(new java.awt.Font("Trajan Pro", 1, 13)); // NOI18N
        jLSaldoJogador1.setForeground(new java.awt.Color(255, 204, 153));
        getContentPane().add(jLSaldoJogador1);
        jLSaldoJogador1.setBounds(110, 240, 90, 15);

        jLSaldoJogador2.setFont(new java.awt.Font("Trajan Pro", 1, 13)); // NOI18N
        jLSaldoJogador2.setForeground(new java.awt.Color(255, 204, 153));
        getContentPane().add(jLSaldoJogador2);
        jLSaldoJogador2.setBounds(1260, 240, 80, 13);

        jLposicaoDialogoComprar.setText("jLabel2");
        getContentPane().add(jLposicaoDialogoComprar);
        jLposicaoDialogoComprar.setBounds(673, 350, 34, 14);

        jLTabuleiro.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ufc/projeto/imagens/background/Tabuleiro.png"))); // NOI18N
        getContentPane().add(jLTabuleiro);
        jLTabuleiro.setBounds(0, 0, 1376, 728);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jCDado1Jogador1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCDado1Jogador1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCDado1Jogador1ActionPerformed

    private void jCDado1Jogador2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCDado1Jogador2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCDado1Jogador2ActionPerformed

    private void formKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_formKeyTyped
       
    }//GEN-LAST:event_formKeyTyped
     
    private void jBFinalizarJogada1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBFinalizarJogada1ActionPerformed
       
    }//GEN-LAST:event_jBFinalizarJogada1ActionPerformed

    private synchronized void efeitoFinalizarJogada(JLabel jogador){
        try {
            new ControladorDeAudio(Midia.CAMINHO_SOM_BOTOES.obterCaminho()).start();
            Thread.sleep(Midia.TEMPO_CRIAR_SOM_BOTAO.obterValor());
            
            if(jogador.equals(jLPersonagemJogador2))
                jBFinalizarJogada1.setIcon(new ImageIcon(getClass().getResource(Midia.IMAGEM_JOGAR_RODADA_NORMAL.obterCaminho())));
            else
                jBFinalizarJogada2.setIcon(new ImageIcon(getClass().getResource(Midia.IMAGEM_JOGAR_RODADA_NORMAL.obterCaminho())));
            
        } catch (InterruptedException ex) {
            Logger.getLogger(BancoImobiliarioGui.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    
    private void preenchendoPerfil(List<Perfil> perfil){
        Perfil per = perfil.get(Jogadores.JOGADOR_1.obterValor());
            jLPersonagem1.setIcon(new ImageIcon(per.obterUrlImagem()));
            jLPersonagemJogador1.setIcon(new ImageIcon(per.obterUtlGif().get(Midia.IMAGEM_FRODO_GIF_FRENTE_PARADO.obterValor())));
            jLNomeDoJagador1.setIcon(new ImageIcon(per.obterUrlNome()));
        per = perfil.get(Jogadores.JOGADOR_2.obterValor());
            jLPersonagem2.setIcon(new ImageIcon(per.obterUrlImagem()));
            jLPersonagemJogador2.setIcon(new ImageIcon(per.obterUtlGif().get(Midia.IMAGEM_FRODO_GIF_FRENTE_PARADO.obterValor())));
            jLNomeDoJagador2.setIcon(new ImageIcon(per.obterUrlNome()));
    }
    
    private void mudarImagemPersonagem(JLabel personagem, URL imagem){
        personagem.setIcon(new ImageIcon(imagem));
    }
    
    private void jBFinalizarJogada2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBFinalizarJogada2ActionPerformed
   
    }//GEN-LAST:event_jBFinalizarJogada2ActionPerformed

    private void jBFinalizarJogada1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBFinalizarJogada1MouseEntered
        jBFinalizarJogada1.setIcon(new ImageIcon(getClass().getResource(Midia.IMAGEM_JOGAR_RODADA_CLARO.obterCaminho())));
    }//GEN-LAST:event_jBFinalizarJogada1MouseEntered

    private void jBFinalizarJogada1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBFinalizarJogada1MouseExited
        jBFinalizarJogada1.setIcon(new ImageIcon(getClass().getResource(Midia.IMAGEM_JOGAR_RODADA_NORMAL.obterCaminho())));
    }//GEN-LAST:event_jBFinalizarJogada1MouseExited

    private void jBFinalizarJogada2MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBFinalizarJogada2MouseEntered
        jBFinalizarJogada2.setIcon(new ImageIcon(getClass().getResource(Midia.IMAGEM_JOGAR_RODADA_CLARO.obterCaminho())));
    }//GEN-LAST:event_jBFinalizarJogada2MouseEntered

    private void jBFinalizarJogada2MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBFinalizarJogada2MouseExited
        jBFinalizarJogada2.setIcon(new ImageIcon(getClass().getResource(Midia.IMAGEM_JOGAR_RODADA_NORMAL.obterCaminho())));
    }//GEN-LAST:event_jBFinalizarJogada2MouseExited

    private void jBFinalizarJogada2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBFinalizarJogada2MouseClicked
       
    }//GEN-LAST:event_jBFinalizarJogada2MouseClicked

    private void jBFinalizarJogada1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBFinalizarJogada1MouseClicked
       
    }//GEN-LAST:event_jBFinalizarJogada1MouseClicked

    private void jBFinalizarJogada1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBFinalizarJogada1MousePressed
          if(jBFinalizarJogada1.isEnabled()){
            jBFinalizarJogada1.setIcon(new ImageIcon(getClass().getResource(Midia.IMAGEM_JOGAR_RODADA_ESCURO.obterCaminho())));

             new Thread(new Runnable() {
                @Override
                public void run() {
                 efeitoFinalizarJogada(jLPersonagemJogador2);
                }
            }).start();
             
            int valorDados = jCDado1Jogador1.getSelectedIndex()+1 + jCDado2Jogador1.getSelectedIndex()+1;

            try {
                mBancoImobiliario.jogarAVez(valorDados);
            } catch (LogradouroNaoPodeSerAdquiridoException ex) {
                Logger.getLogger(BancoImobiliarioGui.class.getName()).log(Level.SEVERE, null, ex);
            } catch (JogadorSemSaldoException ex) {
                Logger.getLogger(BancoImobiliarioGui.class.getName()).log(Level.SEVERE, null, ex);
            } catch (PropriedadeJaAdquiridaException ex) {
                Logger.getLogger(BancoImobiliarioGui.class.getName()).log(Level.SEVERE, null, ex);
            } catch (LogradouroSemPrecoException ex) {
                Logger.getLogger(BancoImobiliarioGui.class.getName()).log(Level.SEVERE, null, ex);
            } catch (PosicaoIvalidaParaLogradouroException ex) {
                Logger.getLogger(BancoImobiliarioGui.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_jBFinalizarJogada1MousePressed

    private void jBFinalizarJogada2MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBFinalizarJogada2MousePressed
         if(jBFinalizarJogada2.isEnabled()){
            jBFinalizarJogada2.setIcon(new ImageIcon(getClass().getResource(Midia.IMAGEM_JOGAR_RODADA_ESCURO.obterCaminho())));

            new Thread(new Runnable() {

                @Override
                public void run() {
                    efeitoFinalizarJogada(jLPersonagemJogador1);
                }
            }).start();
         
            int valorDados = jCDado1Jogador2.getSelectedIndex()+1 + jCDado2Jogador2.getSelectedIndex()+1;
            try {
                mBancoImobiliario.jogarAVez(valorDados);
            } catch (LogradouroNaoPodeSerAdquiridoException ex) {
                Logger.getLogger(BancoImobiliarioGui.class.getName()).log(Level.SEVERE, null, ex);
            } catch (JogadorSemSaldoException ex) {
                Logger.getLogger(BancoImobiliarioGui.class.getName()).log(Level.SEVERE, null, ex);
            } catch (PropriedadeJaAdquiridaException ex) {
                Logger.getLogger(BancoImobiliarioGui.class.getName()).log(Level.SEVERE, null, ex);
            } catch (LogradouroSemPrecoException ex) {
                Logger.getLogger(BancoImobiliarioGui.class.getName()).log(Level.SEVERE, null, ex);
            } catch (PosicaoIvalidaParaLogradouroException ex) {
                Logger.getLogger(BancoImobiliarioGui.class.getName()).log(Level.SEVERE, null, ex);
            }
         }
    }//GEN-LAST:event_jBFinalizarJogada2MousePressed

    private void visualizarLogradouros(Point point){
         try {
            Logradouro logradouro = mBancoImobiliario.getInformacaoLogradoEscolhido(pontosLogradourosGui.get(point));
            DialogoLogradouro dialogoLogradouro = new DialogoMostrarLogradouro(this, logradouro);
        } catch (PosicaoIvalidaParaLogradouroException ex) {
            ex.printStackTrace();
        }
    }
    
    private void jLLogradouro0MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLLogradouro0MouseClicked
        visualizarLogradouros(jLLogradouro0.getLocation());
    }//GEN-LAST:event_jLLogradouro0MouseClicked

    
    private void jLLogradouro1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLLogradouro1MouseClicked
        visualizarLogradouros(jLLogradouro1.getLocation());
    }//GEN-LAST:event_jLLogradouro1MouseClicked

    private void jLLogradouro2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLLogradouro2MouseClicked
         visualizarLogradouros(jLLogradouro2.getLocation());
    }//GEN-LAST:event_jLLogradouro2MouseClicked

    private void jLLogradouro3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLLogradouro3MouseClicked
       visualizarLogradouros(jLLogradouro3.getLocation());
    }//GEN-LAST:event_jLLogradouro3MouseClicked

    private void jLLogradouro4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLLogradouro4MouseClicked
        visualizarLogradouros(jLLogradouro4.getLocation());
    }//GEN-LAST:event_jLLogradouro4MouseClicked

    private void jLLogradouro5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLLogradouro5MouseClicked
        visualizarLogradouros(jLLogradouro5.getLocation());
    }//GEN-LAST:event_jLLogradouro5MouseClicked

    private void jLLogradouro6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLLogradouro6MouseClicked
        visualizarLogradouros(jLLogradouro6.getLocation());
    }//GEN-LAST:event_jLLogradouro6MouseClicked

    private void jLLogradouro7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLLogradouro7MouseClicked
        visualizarLogradouros(jLLogradouro7.getLocation());
    }//GEN-LAST:event_jLLogradouro7MouseClicked

    private void jLLogradouro8MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLLogradouro8MouseClicked
        visualizarLogradouros(jLLogradouro8.getLocation());
    }//GEN-LAST:event_jLLogradouro8MouseClicked

    private void jLLogradouro9MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLLogradouro9MouseClicked
         visualizarLogradouros(jLLogradouro9.getLocation());
    }//GEN-LAST:event_jLLogradouro9MouseClicked

    private void jLLogradouro10MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLLogradouro10MouseClicked
         visualizarLogradouros(jLLogradouro10.getLocation());
    }//GEN-LAST:event_jLLogradouro10MouseClicked

    private void jLLogradouro11MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLLogradouro11MouseClicked
         visualizarLogradouros(jLLogradouro11.getLocation());
    }//GEN-LAST:event_jLLogradouro11MouseClicked

    private void jLLogradouro12MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLLogradouro12MouseClicked
         visualizarLogradouros(jLLogradouro12.getLocation());
    }//GEN-LAST:event_jLLogradouro12MouseClicked

    private void jLLogradouro13MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLLogradouro13MouseClicked
         visualizarLogradouros(jLLogradouro13.getLocation());
    }//GEN-LAST:event_jLLogradouro13MouseClicked

    private void jLLogradouro14MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLLogradouro14MouseClicked
         visualizarLogradouros(jLLogradouro14.getLocation());
    }//GEN-LAST:event_jLLogradouro14MouseClicked

    private void jLLogradouro15MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLLogradouro15MouseClicked
         visualizarLogradouros(jLLogradouro15.getLocation());
    }//GEN-LAST:event_jLLogradouro15MouseClicked

    private void jLLogradouro16KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jLLogradouro16KeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_jLLogradouro16KeyPressed

    private void jLLogradouro16MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLLogradouro16MouseClicked
        visualizarLogradouros(jLLogradouro16.getLocation());
    }//GEN-LAST:event_jLLogradouro16MouseClicked

    private void jLLogradouro17MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLLogradouro17MouseClicked
        visualizarLogradouros(jLLogradouro17.getLocation());
    }//GEN-LAST:event_jLLogradouro17MouseClicked

    private void jLLogradouro18MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLLogradouro18MouseClicked
        visualizarLogradouros(jLLogradouro18.getLocation());
    }//GEN-LAST:event_jLLogradouro18MouseClicked

    private void jLLogradouro19MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLLogradouro19MouseClicked
        visualizarLogradouros(jLLogradouro19.getLocation());
    }//GEN-LAST:event_jLLogradouro19MouseClicked
    
    private synchronized void movimentar(int posicoes, JLabel jogador, Jogador jogado){
        int diferencial, posicaoInicial;
        if(jogador.equals(jLPersonagemJogador1)){
            diferencial = MovimentacaoPersonagemGui.POSICAO_DIFERENCIAL_JG1.obterValor();
            posicaoInicial = MovimentacaoPersonagemGui.POSICAO_INICIAl_JG1.obterValor();
        }
        else{
            diferencial = MovimentacaoPersonagemGui.POSICAO_DIFERENCIAL_JG2.obterValor();
            posicaoInicial = MovimentacaoPersonagemGui.POSICAO_INICIAl_JG2.obterValor();
        }
        
        
        
          for(int i=1; i<=(posicoes*MovimentacaoPersonagemGui.SOMATORIA_PULOS.obterValor()); i++){
                
                if(jogador.getX() == posicaoInicial && (jogador.getY() <= MovimentacaoPersonagemGui.POSICAO_MAXIMA_CORDENADA_Y.obterValor() && jogador.getY() > MovimentacaoPersonagemGui.POSICAO_MINIMA_CORDENADA_Y.obterValor())){
                    jogador.setLocation(jogador.getX(), jogador.getY()-1);
                    mudarImagemPersonagem(jogador, jogado.obterPerfil().obterUtlGif().get(Midia.IMAGEM_GIF_COSTAS_MOVIMENTACAO_VALOR.obterValor()));
                }else if(jogador.getY() == MovimentacaoPersonagemGui.POSICAO_MINIMA_CORDENADA_Y.obterValor() && (jogador.getX() >= posicaoInicial && jogador.getX() < diferencial)){
                    jogador.setLocation(jogador.getX()+1, jogador.getY());
                    mudarImagemPersonagem(jogador, jogado.obterPerfil().obterUtlGif().get(Midia.IMAGEM_GIF_DIREITA_MOVIMENTACAO_VALOR.obterValor()));
                }else if(jogador.getX() == diferencial && (jogador.getY() >= MovimentacaoPersonagemGui.POSICAO_MINIMA_CORDENADA_Y.obterValor() && jogador.getY() < MovimentacaoPersonagemGui.POSICAO_MAXIMA_CORDENADA_Y.obterValor())){
                    jogador.setLocation(jogador.getX(), jogador.getY()+1);
                    mudarImagemPersonagem(jogador, jogado.obterPerfil().obterUtlGif().get(Midia.IMAGEM_GIF_FRENTE_MOVIMENTACAO_VALOR.obterValor()));
                }else if(jogador.getY() == MovimentacaoPersonagemGui.POSICAO_MAXIMA_CORDENADA_Y.obterValor() && (jogador.getX() <= diferencial && jogador.getX() > posicaoInicial)){
                    jogador.setLocation(jogador.getX()-1, jogador.getY());
                    mudarImagemPersonagem(jogador, jogado.obterPerfil().obterUtlGif().get(Midia.IMAGEM_GIF_ESQUERDA_MOVIMENTACAO_VALOR.obterValor()));
                } 
                try {
                    Thread.sleep(MovimentacaoPersonagemGui.TEMPO_DE_UM_PASSO.obterValor());
                } catch (InterruptedException ex) {
                    Logger.getLogger(BancoImobiliarioGui.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
    }
    /*
    /**
     * @param args the command line arguments
     *
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BancoImobiliarioGui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BancoImobiliarioGui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BancoImobiliarioGui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BancoImobiliarioGui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form 
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new BancoImobiliarioGui(null).setVisible(true);
            }
        });
    }
    */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextPane PTPossesJogador1;
    private javax.swing.JTextPane PTPossesJogador2;
    private javax.swing.JButton jBFinalizarJogada1;
    private javax.swing.JButton jBFinalizarJogada2;
    private javax.swing.JComboBox jCDado1Jogador1;
    private javax.swing.JComboBox jCDado1Jogador2;
    private javax.swing.JComboBox jCDado2Jogador1;
    private javax.swing.JComboBox jCDado2Jogador2;
    private javax.swing.JLabel jLCartasJogador1;
    private javax.swing.JLabel jLCartasJogador2;
    private javax.swing.JLabel jLCorrecaoGif;
    private javax.swing.JLabel jLImagemCentral;
    private javax.swing.JLabel jLLogradouro0;
    private javax.swing.JLabel jLLogradouro1;
    private javax.swing.JLabel jLLogradouro10;
    private javax.swing.JLabel jLLogradouro11;
    private javax.swing.JLabel jLLogradouro12;
    private javax.swing.JLabel jLLogradouro13;
    private javax.swing.JLabel jLLogradouro14;
    private javax.swing.JLabel jLLogradouro15;
    private javax.swing.JLabel jLLogradouro16;
    private javax.swing.JLabel jLLogradouro17;
    private javax.swing.JLabel jLLogradouro18;
    private javax.swing.JLabel jLLogradouro19;
    private javax.swing.JLabel jLLogradouro2;
    private javax.swing.JLabel jLLogradouro3;
    private javax.swing.JLabel jLLogradouro4;
    private javax.swing.JLabel jLLogradouro5;
    private javax.swing.JLabel jLLogradouro6;
    private javax.swing.JLabel jLLogradouro7;
    private javax.swing.JLabel jLLogradouro8;
    private javax.swing.JLabel jLLogradouro9;
    private javax.swing.JLabel jLNomeDoJagador1;
    private javax.swing.JLabel jLNomeDoJagador2;
    private javax.swing.JLabel jLPersonagem1;
    private javax.swing.JLabel jLPersonagem2;
    private javax.swing.JLabel jLPersonagemJogador1;
    private javax.swing.JLabel jLPersonagemJogador2;
    private javax.swing.JLabel jLSaldoJogador1;
    private javax.swing.JLabel jLSaldoJogador2;
    private javax.swing.JLabel jLTabuleiro;
    private javax.swing.JLabel jLposicaoDialogoComprar;
    private javax.swing.JScrollPane jSPossesjogador1;
    private javax.swing.JScrollPane jSPossesjogador2;
    // End of variables declaration//GEN-END:variables

    @Override
    public void andarCasas(final Jogador jogador, final int quantidadePulos) {
        if(listaJogadores.get(Jogadores.JOGADOR_1.obterValor()).equals(jogador)){
           
            new Thread(new Runnable() {

                @Override
                public void run() {
                    movimentar(quantidadePulos, jLPersonagemJogador1, jogador);
                    mudarImagemPersonagem(jLPersonagemJogador1, jogador.obterPerfil().obterUtlGif().get(Midia.IMAGEM_GIF_FRENTE_PARADO_VALOR.obterValor()));
                }
            }).start();
        
        }else{
            
            new Thread(new Runnable() {

                @Override
                public void run() {
                    movimentar(quantidadePulos, jLPersonagemJogador2, jogador);
                    mudarImagemPersonagem(jLPersonagemJogador2, jogador.obterPerfil().obterUtlGif().get(Midia.IMAGEM_GIF_FRENTE_PARADO_VALOR.obterValor()));
                }
            }).start();
        }
    }

    @Override
    public void jogoTerminado(Jogador vencedor) {
    
    }

    @Override
    public void atualizarJogo(Iterator<Jogador> listaJogadores) {
            while(listaJogadores.hasNext()){
                Jogador jogador = listaJogadores.next();
                
                if(this.listaJogadores.get(Jogadores.JOGADOR_1.obterValor()).equals(jogador)){
                    jLSaldoJogador1.setText(jogador.obterSaldo()+"");
                    Iterator<LogradouroAdquirivel> logradouros = jogador.obterLogradourosAdquiridos();
                    PTPossesJogador1.setText(null);
                    while(logradouros.hasNext()){
                        Logradouro logradouro = logradouros.next();
                        PTPossesJogador1.setText(PTPossesJogador1.getText()+"\n"+logradouro.obterNome());
                    }
                }else{
                    jLSaldoJogador2.setText(jogador.obterSaldo()+"");
                    Iterator<LogradouroAdquirivel> logradouros = jogador.obterLogradourosAdquiridos();
                    PTPossesJogador2.setText(null);
                    while(logradouros.hasNext()){
                        Logradouro logradouro = logradouros.next();
                        PTPossesJogador2.setText(PTPossesJogador2.getText()+"\n"+logradouro.obterNome());
                    }
                }
        }
    }

    @Override
    public void mudarJogadores(Jogador jogadorDaVez) {
        if(listaJogadores.get(Jogadores.JOGADOR_1.obterValor()).equals(jogadorDaVez)){
            jBFinalizarJogada1.setEnabled(true);
            jBFinalizarJogada2.setEnabled(false);
        }else{
            jBFinalizarJogada2.setEnabled(true);
            jBFinalizarJogada1.setEnabled(false);
        }
    }

    @Override
    public boolean logradouroAcionado(Logradouro logradouroAcionado, int tipoMensagem) {
        DialogoLogradouro dialogo = new CriadorDialogo().obterDialogo(this, tipoMensagem, logradouroAcionado);
        return dialogo.obterConfirmacao();
    }
}
