/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ufc.projeto.visao;

import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import ufc.projeto.modelo.Logradouro;
import ufc.projeto.modelo.excecoes.LogradouroSemPrecoException;

/**
 *
 * @author Loopback
 */
public class PainelVendaLogradouro extends PainelLogradouro {

    private final Logradouro logradouro;
    
    public PainelVendaLogradouro(Logradouro logradouro) {
        super(logradouro);
        this.logradouro = logradouro;
        initComponents();
        preenchendoInformacoes();
    }
    
    private void preenchendoInformacoes(){
        ljImagemLogradouro.setIcon(new ImageIcon(logradouro.obterUrlImagem()));
        jlNomeLogradouro1.setText(logradouro.obterNome());
        jtaDescricao.setText(logradouro.obterDescriao());
        try {
            ljPreco.setText(logradouro.obterPreco()+"");
        } catch (LogradouroSemPrecoException ex) {
            Logger.getLogger(PainelVendaLogradouro.class.getName()).log(Level.SEVERE, null, ex);
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ljImagemLogradouro = new javax.swing.JLabel();
        ljPreco = new javax.swing.JLabel();
        jtaDescricao = new javax.swing.JTextArea();
        btNComprar = new javax.swing.JButton();
        btComprar = new javax.swing.JButton();
        jlNomeLogradouro1 = new javax.swing.JLabel();
        ljModeloPreco = new javax.swing.JLabel();
        jlBackground = new javax.swing.JLabel();

        setMaximumSize(new java.awt.Dimension(480, 310));
        setMinimumSize(new java.awt.Dimension(480, 310));
        setLayout(null);
        add(ljImagemLogradouro);
        ljImagemLogradouro.setBounds(80, 60, 130, 120);

        ljPreco.setFont(new java.awt.Font("Trajan Pro", 1, 13)); // NOI18N
        ljPreco.setText("125");
        add(ljPreco);
        ljPreco.setBounds(140, 200, 60, 20);

        jtaDescricao.setEditable(false);
        jtaDescricao.setBackground(new java.awt.Color(237, 221, 202));
        jtaDescricao.setColumns(20);
        jtaDescricao.setFont(new java.awt.Font("Trajan Pro", 1, 12)); // NOI18N
        jtaDescricao.setLineWrap(true);
        jtaDescricao.setRows(5);
        jtaDescricao.setBorder(null);
        add(jtaDescricao);
        jtaDescricao.setBounds(214, 60, 210, 120);

        btNComprar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ufc/projeto/imagens/botoes/NaoComprarDoPergaminho.png"))); // NOI18N
        btNComprar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btNComprar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btNComprarMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btNComprarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btNComprarMouseExited(evt);
            }
        });
        btNComprar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btNComprarActionPerformed(evt);
            }
        });
        add(btNComprar);
        btNComprar.setBounds(240, 250, 120, 37);

        btComprar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ufc/projeto/imagens/botoes/ComprarDoPergaminho.jpg"))); // NOI18N
        btComprar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btComprar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btComprarMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btComprarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btComprarMouseExited(evt);
            }
        });
        add(btComprar);
        btComprar.setBounds(130, 250, 104, 37);

        jlNomeLogradouro1.setFont(new java.awt.Font("Trajan Pro", 1, 14)); // NOI18N
        jlNomeLogradouro1.setText("NOMELOGRADOURO");
        add(jlNomeLogradouro1);
        jlNomeLogradouro1.setBounds(80, 20, 270, 20);

        ljModeloPreco.setFont(new java.awt.Font("Trajan Pro", 1, 13)); // NOI18N
        ljModeloPreco.setText("Preço: ");
        add(ljModeloPreco);
        ljModeloPreco.setBounds(80, 200, 60, 20);

        jlBackground.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ufc/projeto/imagens/background/PergaminhoDeMensagens.png"))); // NOI18N
        jlBackground.setName(""); // NOI18N
        add(jlBackground);
        jlBackground.setBounds(0, 0, 480, 310);
    }// </editor-fold>//GEN-END:initComponents

    private void btNComprarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btNComprarMouseEntered
        btNComprar.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
    }//GEN-LAST:event_btNComprarMouseEntered

    private void btNComprarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btNComprarMouseExited
        btNComprar.setBorder(null);
    }//GEN-LAST:event_btNComprarMouseExited

    private void btNComprarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btNComprarMouseClicked
        eventosDialogo.cliqueBotao2();
    }//GEN-LAST:event_btNComprarMouseClicked

    private void btComprarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btComprarMouseClicked
        eventosDialogo.cliqueBotao1();
    }//GEN-LAST:event_btComprarMouseClicked

    private void btComprarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btComprarMouseEntered
        btComprar.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
    }//GEN-LAST:event_btComprarMouseEntered

    private void btComprarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btComprarMouseExited
        btComprar.setBorder(null);
    }//GEN-LAST:event_btComprarMouseExited

    private void btNComprarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btNComprarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btNComprarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btComprar;
    private javax.swing.JButton btNComprar;
    private javax.swing.JLabel jlBackground;
    private javax.swing.JLabel jlNomeLogradouro1;
    private javax.swing.JTextArea jtaDescricao;
    private javax.swing.JLabel ljImagemLogradouro;
    private javax.swing.JLabel ljModeloPreco;
    private javax.swing.JLabel ljPreco;
    // End of variables declaration//GEN-END:variables
}
