/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ufc.projeto.visao;

import javax.swing.ImageIcon;
import ufc.projeto.modelo.Logradouro;

/**
 *
 * @author Loopback
 */
public class PainelMostrarLogradouro extends PainelLogradouro {

    private final Logradouro logradouro;
    
    public PainelMostrarLogradouro(Logradouro logradouro) {
        super(logradouro);
        this.logradouro = logradouro;
        initComponents();
        preenchendoInformacoes();
    }
    
    private void preenchendoInformacoes(){
        ljImagemLogradouro.setIcon(new ImageIcon(logradouro.obterUrlImagem()));
        jtaDescricao.setText(logradouro.obterDescriao());
        jlNomeLogradouro.setText(logradouro.obterNome());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ljImagemLogradouro = new javax.swing.JLabel();
        jlNomeLogradouro = new javax.swing.JLabel();
        jtaDescricao = new javax.swing.JTextArea();
        btContinuar = new javax.swing.JButton();
        jlBackground = new javax.swing.JLabel();

        setMaximumSize(new java.awt.Dimension(480, 310));
        setMinimumSize(new java.awt.Dimension(480, 310));
        setLayout(null);
        add(ljImagemLogradouro);
        ljImagemLogradouro.setBounds(80, 60, 130, 120);

        jlNomeLogradouro.setFont(new java.awt.Font("Trajan Pro", 1, 14)); // NOI18N
        jlNomeLogradouro.setText("NOMELOGRADOURO");
        add(jlNomeLogradouro);
        jlNomeLogradouro.setBounds(80, 20, 270, 20);

        jtaDescricao.setEditable(false);
        jtaDescricao.setBackground(new java.awt.Color(237, 221, 202));
        jtaDescricao.setColumns(20);
        jtaDescricao.setFont(new java.awt.Font("Trajan Pro", 1, 12)); // NOI18N
        jtaDescricao.setLineWrap(true);
        jtaDescricao.setRows(5);
        jtaDescricao.setBorder(null);
        add(jtaDescricao);
        jtaDescricao.setBounds(214, 60, 210, 120);

        btContinuar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ufc/projeto/imagens/botoes/Continuar.jpg"))); // NOI18N
        btContinuar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btContinuar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btContinuarMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btContinuarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btContinuarMouseExited(evt);
            }
        });
        add(btContinuar);
        btContinuar.setBounds(190, 250, 104, 37);

        jlBackground.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ufc/projeto/imagens/background/PergaminhoDeMensagens.png"))); // NOI18N
        jlBackground.setName(""); // NOI18N
        add(jlBackground);
        jlBackground.setBounds(0, 0, 480, 310);
    }// </editor-fold>//GEN-END:initComponents

    private void btContinuarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btContinuarMouseEntered
        btContinuar.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
    }//GEN-LAST:event_btContinuarMouseEntered

    private void btContinuarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btContinuarMouseExited
        btContinuar.setBorder(null);
    }//GEN-LAST:event_btContinuarMouseExited

    private void btContinuarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btContinuarMouseClicked
        eventosDialogo.cliqueBotao1();
    }//GEN-LAST:event_btContinuarMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btContinuar;
    private javax.swing.JLabel jlBackground;
    private javax.swing.JLabel jlNomeLogradouro;
    private javax.swing.JTextArea jtaDescricao;
    private javax.swing.JLabel ljImagemLogradouro;
    // End of variables declaration//GEN-END:variables
}
