/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package ufc.projeto.visao;

import static java.lang.Thread.sleep;
import java.util.ArrayList;
import ufc.projeto.gui.controlador.midia.AePlayWave;
import java.util.Iterator;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import ufc.projeto.gui.controlador.midia.FabricaDeImagens;
import ufc.projeto.gui.enumeracoes.Midia;
import ufc.projeto.modelo.Perfil;

/**
 *
 * @author Robson Cavalcante
 */
public class SelecionaJogadoresGui extends javax.swing.JFrame {

    /**
     * Creates new form TelaConfigurarJogadores
     */
    
    private Iterator<Perfil> imagensJogador1;
    private Iterator<Perfil> imagensJogador2;
    private final FabricaDeImagens fabricaDeImagens;
    private Perfil perfilJg1Selecionado;
    private Perfil perfilJg2Selecionado;
    
    public SelecionaJogadoresGui() {
        initComponents();
        setLocationRelativeTo(null);
    
        fabricaDeImagens = new FabricaDeImagens();
        imagensJogador1 = fabricaDeImagens.obterImagens();
        imagensJogador2 = fabricaDeImagens.obterImagens();
        
        
        if(imagensJogador1.hasNext()){
            Perfil perfil = imagensJogador1.next();
            perfilJg1Selecionado = perfil;
            imagemJogador1.setIcon(new ImageIcon(perfil.getUrlImagem()));
            jLNomeDoPersonagem1.setIcon(new ImageIcon(perfil.getUrlNome()));
            jLGifPersonagens1.setIcon(new ImageIcon(perfil.getUtlGif()));
        }
        
        if(imagensJogador2.hasNext()){
            imagensJogador2.next();
            Perfil perfil = imagensJogador2.next();
            perfilJg2Selecionado = perfil;
            imagemJogador2.setIcon(new ImageIcon(perfil.getUrlImagem()));
            jLNomeDoPersonagem2.setIcon(new ImageIcon(perfil.getUrlNome()));
            jLGifPersonagens2.setIcon(new ImageIcon(perfil.getUtlGif()));
        }
        
            
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    
    private void ModificarPerfilJogador1(){
        if(imagensJogador1.hasNext()){
            Perfil perfil = imagensJogador1.next();
            if(!perfilJg2Selecionado.equals(perfil)){
                perfilJg1Selecionado = perfil;
                imagemJogador1.setIcon(new ImageIcon(perfil.getUrlImagem()));
                jLNomeDoPersonagem1.setIcon(new ImageIcon(perfil.getUrlNome()));
                jLGifPersonagens1.setIcon(new ImageIcon(perfil.getUtlGif()));
            }else{
                ModificarPerfilJogador1();
            }
        }
        else{
            imagensJogador1 = fabricaDeImagens.obterImagens();
            Perfil perfil = imagensJogador1.next();
            if(!perfilJg2Selecionado.equals(perfil)){
                perfilJg1Selecionado = perfil;
                imagemJogador1.setIcon(new ImageIcon(perfil.getUrlImagem()));
                jLNomeDoPersonagem1.setIcon(new ImageIcon(perfil.getUrlNome()));
                jLGifPersonagens1.setIcon(new ImageIcon(perfil.getUtlGif()));
            }else{
                ModificarPerfilJogador1();
            }
        }
    }
    
        
    private void ModificarPerfilJogador2(){
        if(imagensJogador2.hasNext()){
            Perfil perfil = imagensJogador2.next();
            if(!perfilJg1Selecionado.equals(perfil)){
                perfilJg2Selecionado = perfil;
                imagemJogador2.setIcon(new ImageIcon(perfil.getUrlImagem()));
                jLNomeDoPersonagem2.setIcon(new ImageIcon(perfil.getUrlNome()));
                jLGifPersonagens2.setIcon(new ImageIcon(perfil.getUtlGif()));
            }else{
                ModificarPerfilJogador2();
            }
        }else{
            imagensJogador2 = fabricaDeImagens.obterImagens();
            Perfil perfil = imagensJogador2.next();
            if(!perfilJg1Selecionado.equals(perfil)){
                perfilJg2Selecionado = perfil;
                imagemJogador2.setIcon(new ImageIcon(perfil.getUrlImagem()));
                jLNomeDoPersonagem2.setIcon(new ImageIcon(perfil.getUrlNome()));
                jLGifPersonagens2.setIcon(new ImageIcon(perfil.getUtlGif()));
            }else{
                ModificarPerfilJogador2();
            }
        }
    }
    
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLGifPersonagens1 = new javax.swing.JLabel();
        jLGifPersonagens2 = new javax.swing.JLabel();
        jLNomeDoPersonagem2 = new javax.swing.JLabel();
        jLNomeDoPersonagem1 = new javax.swing.JLabel();
        btVoltar = new javax.swing.JButton();
        btIniciar = new javax.swing.JButton();
        btProximaImagemJogador1 = new javax.swing.JButton();
        btProximaImagemJogador2 = new javax.swing.JButton();
        imagemJogador2 = new javax.swing.JLabel();
        imagemJogador1 = new javax.swing.JLabel();
        background = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1376, 728));
        setUndecorated(true);
        setResizable(false);
        getContentPane().setLayout(null);

        jLGifPersonagens1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ufc/projeto/imagens/personagens/Conversa.gif"))); // NOI18N
        getContentPane().add(jLGifPersonagens1);
        jLGifPersonagens1.setBounds(230, 110, 230, 160);

        jLGifPersonagens2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ufc/projeto/imagens/personagens/Costas.gif"))); // NOI18N
        getContentPane().add(jLGifPersonagens2);
        jLGifPersonagens2.setBounds(960, 110, 200, 130);

        jLNomeDoPersonagem2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ufc/projeto/imagens/background/ArwenNome.png"))); // NOI18N
        getContentPane().add(jLNomeDoPersonagem2);
        jLNomeDoPersonagem2.setBounds(1190, 230, 90, 20);

        jLNomeDoPersonagem1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ufc/projeto/imagens/background/FrodoNome.png"))); // NOI18N
        getContentPane().add(jLNomeDoPersonagem1);
        jLNomeDoPersonagem1.setBounds(110, 230, 90, 20);

        btVoltar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ufc/projeto/imagens/botoes/VoltarNormal.jpg"))); // NOI18N
        btVoltar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btVoltarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btVoltarMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btVoltarMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                btVoltarMouseReleased(evt);
            }
        });
        btVoltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btVoltarActionPerformed(evt);
            }
        });
        getContentPane().add(btVoltar);
        btVoltar.setBounds(1130, 580, 170, 50);

        btIniciar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ufc/projeto/imagens/botoes/JogarNormal.png"))); // NOI18N
        btIniciar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btIniciarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btIniciarMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btIniciarMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                btIniciarMouseReleased(evt);
            }
        });
        btIniciar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btIniciarActionPerformed(evt);
            }
        });
        getContentPane().add(btIniciar);
        btIniciar.setBounds(60, 580, 170, 50);

        btProximaImagemJogador1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ufc/projeto/imagens/botoes/setaBotaoPassar.jpg"))); // NOI18N
        btProximaImagemJogador1.setBorder(null);
        btProximaImagemJogador1.setBorderPainted(false);
        btProximaImagemJogador1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btProximaImagemJogador1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btProximaImagemJogador1MouseExited(evt);
            }
        });
        btProximaImagemJogador1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btProximaImagemJogador1ActionPerformed(evt);
            }
        });
        getContentPane().add(btProximaImagemJogador1);
        btProximaImagemJogador1.setBounds(100, 270, 110, 30);

        btProximaImagemJogador2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ufc/projeto/imagens/botoes/setaBotaoPassar.jpg"))); // NOI18N
        btProximaImagemJogador2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btProximaImagemJogador2ActionPerformed(evt);
            }
        });
        getContentPane().add(btProximaImagemJogador2);
        btProximaImagemJogador2.setBounds(1180, 270, 110, 30);

        imagemJogador2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ufc/projeto/imagens/personagens/Arwen.png"))); // NOI18N
        getContentPane().add(imagemJogador2);
        imagemJogador2.setBounds(1130, 100, 170, 130);

        imagemJogador1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ufc/projeto/imagens/personagens/Frodo.png"))); // NOI18N
        getContentPane().add(imagemJogador1);
        imagemJogador1.setBounds(50, 100, 190, 140);

        background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ufc/projeto/imagens/background/TelaDeSeleçãoDePersonagens.png"))); // NOI18N
        getContentPane().add(background);
        background.setBounds(0, 0, 1380, 730);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btIniciarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btIniciarActionPerformed
        btIniciar.setIcon(new ImageIcon(getClass().getResource(Midia.IMAGEM_JOGAR_ESCURO.obterCaminho())));
        
        new Thread(new Runnable() {
            @Override
            public void run() {
                try {
                    new AePlayWave(Midia.CAMINHO_SOM_BOTOES.obterCaminho()).start();
                    Thread.sleep(Midia.TEMPO_CRIAR_SOM_BOTAO.obterTempo());
                    btIniciar.setIcon(new ImageIcon(getClass().getResource(Midia.IMAGEM_JOGAR_NORMAL.obterCaminho())));
                    
                } catch (InterruptedException ex) {
                    Logger.getLogger(SelecionaJogadoresGui.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        }).start();
        
        new Thread(new Runnable() {

            @Override
            public void run() {
               try {
                    sleep(500);
                    List<Perfil> lista = new ArrayList<>();
                    lista.add(perfilJg1Selecionado);
                    lista.add(perfilJg2Selecionado);
                    new BancoImobiliarioGui(lista).setVisible(true);
                } catch (InterruptedException ex) {
                    Logger.getLogger(InicioGui.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        }).start();
    }//GEN-LAST:event_btIniciarActionPerformed

    private void btIniciarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btIniciarMouseEntered
        btIniciar.setIcon(new ImageIcon(getClass().getResource(Midia.IMAGEM_JOGAR_CLARO.obterCaminho())));
    }//GEN-LAST:event_btIniciarMouseEntered

    private void btIniciarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btIniciarMouseExited
        btIniciar.setIcon(new ImageIcon(getClass().getResource(Midia.IMAGEM_JOGAR_NORMAL.obterCaminho())));
    }//GEN-LAST:event_btIniciarMouseExited

    private void btIniciarMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btIniciarMousePressed
        
    }//GEN-LAST:event_btIniciarMousePressed

    private void btIniciarMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btIniciarMouseReleased
        
    }//GEN-LAST:event_btIniciarMouseReleased

    private void btProximaImagemJogador2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btProximaImagemJogador2ActionPerformed
        ModificarPerfilJogador2();
    }//GEN-LAST:event_btProximaImagemJogador2ActionPerformed

    private void btProximaImagemJogador1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btProximaImagemJogador1ActionPerformed
        ModificarPerfilJogador1();
    }//GEN-LAST:event_btProximaImagemJogador1ActionPerformed

    private void btVoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btVoltarActionPerformed
         btVoltar.setIcon(new ImageIcon(getClass().getResource(Midia.IMAGEM_VOLTAR_ESCURO.obterCaminho())));
        
          new Thread(new Runnable() {
            @Override
            public void run() {
                try {
                    new AePlayWave(Midia.CAMINHO_SOM_BOTOES.obterCaminho()).start();
                    Thread.sleep(Midia.CAMINHO_SOM_BOTOES.obterTempo());
                    btVoltar.setIcon(new ImageIcon(getClass().getResource(Midia.IMAGEM_VOLTAR_NORMAL.obterCaminho())));
                    dispose();
                } catch (InterruptedException ex) {
                    Logger.getLogger(SelecionaJogadoresGui.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        }).start();
            
          new Thread(new Runnable() {

            @Override
            public void run() {
               try {
                    sleep(500);
                    new InicioGui().setVisible(true);
                } catch (InterruptedException ex) {
                    Logger.getLogger(InicioGui.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        }).start();
    }//GEN-LAST:event_btVoltarActionPerformed

    private void btVoltarMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btVoltarMouseReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_btVoltarMouseReleased

    private void btVoltarMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btVoltarMousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_btVoltarMousePressed

    private void btVoltarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btVoltarMouseExited
         btVoltar.setIcon(new ImageIcon(getClass().getResource(Midia.IMAGEM_VOLTAR_NORMAL.obterCaminho())));
    }//GEN-LAST:event_btVoltarMouseExited

    private void btVoltarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btVoltarMouseEntered
        btVoltar.setIcon(new ImageIcon(getClass().getResource(Midia.IMAGEM_VOLTAR_CLARO.obterCaminho())));
    }//GEN-LAST:event_btVoltarMouseEntered

    private void btProximaImagemJogador1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btProximaImagemJogador1MouseEntered
        btProximaImagemJogador1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
    }//GEN-LAST:event_btProximaImagemJogador1MouseEntered

    private void btProximaImagemJogador1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btProximaImagemJogador1MouseExited
        btProximaImagemJogador1.setBorder(null);
    }//GEN-LAST:event_btProximaImagemJogador1MouseExited

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SelecionaJogadoresGui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SelecionaJogadoresGui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SelecionaJogadoresGui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SelecionaJogadoresGui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SelecionaJogadoresGui().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel background;
    private javax.swing.JButton btIniciar;
    private javax.swing.JButton btProximaImagemJogador1;
    private javax.swing.JButton btProximaImagemJogador2;
    private javax.swing.JButton btVoltar;
    private javax.swing.JLabel imagemJogador1;
    private javax.swing.JLabel imagemJogador2;
    private javax.swing.JLabel jLGifPersonagens1;
    private javax.swing.JLabel jLGifPersonagens2;
    private javax.swing.JLabel jLNomeDoPersonagem1;
    private javax.swing.JLabel jLNomeDoPersonagem2;
    // End of variables declaration//GEN-END:variables
}
